### ISSUE TITLE
Tests in cities_light/test.py failed

### ISSUE THREAD

**Issue by greenday2** [yourlabs/django-cities-light#107]
Branch stable/3.x.x
Django 1.6.11
Run test_project/manage.py test cities_light command have result:
Creating test database for alias 'default'...
.FFF
======================================================================
FAIL: testCountryFormNameAndContinentAlone (cities_light.tests.FormTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/greenday/Dev/django-cities-light/cities_light/tests.py", line 13, in testCountryFormNameAndContinentAlone
    self.assertTrue(form.is_valid())
AssertionError: False is not true

======================================================================
FAIL: testCityAsciiAndSlug (cities_light.tests.SaveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/greenday/Dev/django-cities-light/cities_light/tests.py", line 36, in testCityAsciiAndSlug
    self.assertEqual(city.name_ascii, 'ao e')
AssertionError: 'ao eu' != 'ao e'
- ao eu
?     -
+ ao e

======================================================================
FAIL: testCountryAsciiAndSlug (cities_light.tests.SaveTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/greenday/Dev/django-cities-light/cities_light/tests.py", line 29, in testCountryAsciiAndSlug
    self.assertEqual(country.name_ascii, 'ao e')
AssertionError: 'ao eu' != 'ao e'
- ao eu
?     -
+ ao e

----------------------------------------------------------------------
Ran 4 tests in 0.008s

FAILED (failures=3)
Destroying test database for alias 'default'...

**Comment by jpic** [comment]
I'm aware of this and have fixed it in my branch dj19, where I also leverage django-dbdiff, will push it this weekend and sign a release hopefully !

**Comment by jpic** [comment]
Are you still on 1.6 ? @max-arnold I was hoping to drop support for that version in next release

**Comment by max-arnold** [comment]
No, we do not depend on Django 1.6.

**Comment by jpic** [comment]
Nice, thanks !

I think PR #102 will pass tests now - old ones, and new ones - on django
1.7 to 1.9. It probably doesn't break dj16 support in runtime code, but
definitely does in testcode (new migration test).

#102 fixes this bug and updates the test framework, so if you're into some
testing action then it would be preferable to take a look at it.

Closing
