### ISSUE TITLE
Not importing all cities

### ISSUE THREAD

**Issue by jantos** [yourlabs/django-cities-light#110]
When I run the import script, it seems to skip ~6k cities.

I am using CITIES_LIGHT_CITY_SOURCES = ['http://download.geonames.org/export/dump/cities1000.zip']
Mac box:
Django 1.9.2
Cities_light 3.2.0
Python 2.7.9 
MYSQL 5.6.21

Linux box: Centos
Django 1.9.2
Cities_light 3.2.0
Python 2.7.11
MYSQL 5.5.48-cll

example of how it is skipping entries:
2992741 Monte-Carlo (NOT IMPORTING)
2993458 Monaco  (IMPORTING)
3009937 La Condamine    (NOT IMPORTING)

I end up with 139769 entries in my cities table, but the cities1000.txt file has 145741 lines. 
There are no error messages at all and when I look through the log the "2992741" or "Monte-Carlo" never shows up.

**Comment by max-arnold** [comment]
The cities1000.txt contains different object types (see the full list here http://www.geonames.org/export/codes.html#P). Monte-Carlo and La Condamine both have PPLX feature code (section of populated place) and were filtered out in the following PR https://github.com/yourlabs/django-cities-light/pull/104.

Below is the full list of Monaco subdivisions (Monaco itself is PPLC, its quarters are PPLX):

```
2992741	Monte-Carlo	Monte-Carlo	Monte Carlo,Monte Karlo,Monte Karló,Monte-Karlo,Montecarlo,XMM,Монте-Карло	43.73976	7.42732	P	PPLX	MC		00				16012		45	Europe/Monaco	2013-03-22
2993458	Monaco	Monaco	MCM,Monaco,Monaco-Ville,Monako,Mònaco,Mónaco,Mónakó,Μονακό,Монако	43.73333	7.41667	P	PPLC	MC		00				32965		62	Europe/Monaco	2014-01-26
3009937	La Condamine	La Condamine	Condamine,La Condamine,La-Kondamin,Ла-Кондамин	43.73439	7.42024	P	PPLX	MC		00				12167		16	Europe/Monaco	2013-03-22
3017814	Fontvieille	Fontvieille	Fontvieille,Fonv'ej,Фонвьей	43.72687	7.41766	P	PPLX	MC		00				3602		9	Europe/Monaco	2013-08-18
3225774	Saint-Roman	Saint-Roman		43.7489	7.43423	P	PPLX	MC		00				3000		59	Europe/Monaco	2013-02-07
3319177	Moneghetti	Moneghetti	Les Moneghetti,Monegetti,Moneghetti,Monegue,Монегетти	43.73679	7.41647	P	PPLX	MC		00				3000		99	Europe/Monaco	2014-07-30
```

Note that according to https://en.wikipedia.org/wiki/Les_Moneghetti, Les Moneghetti seems to be incorporated in La Condamine.

You can include all of them by overriding the `CITIES_LIGHT_INCLUDE_CITY_TYPES` setting using the following value (note the 'PPLX' at the end):

```
CITIES_LIGHT_INCLUDE_CITY_TYPES = ['PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLF', 'PPLG', 'PPLL', 'PPLR', 'PPLS', 'STLMT', 'PPLX',]
```

But this will also import a lot of objects which are not cities, for example 23 Budapest districts https://en.wikipedia.org/wiki/Budapest#Districts or Hollywood which belongs to Los Angeles city.

You can list all skipped PPLX entries using this command and decide if you need all of them (2339 in total):

```
grep PPLX cities1000.txt
```

There are no clean way to separate cities from non-cities (districts, neigbhorhoods, etc) so I can suggest different possible approaches:

1. Discuss the status of Monaco wards/quarters with geonames.org maintainers
2. Change the setting as described above and import 2339 additional objects
3. Change the setting AND implement more granular filtering by adding your own `city_items_pre_import` signal handler. For example you can import PPLX entries for some countries and ignore them for others.

@jpic James, what is your opinion on importing or not importing PPLX by default? We can err on any side, but geo data is messy and I see no clean way to make everyone happy.

**Comment by jantos** [comment]
@max-arnold thanks for you awesome and easy to understand answer! I really appreciate it and it helps a lot.

**Comment by max-arnold** [comment]
@jantos Great! I'll close this issue in the next few days if you do not have any objections.

**Comment by jantos** [comment]
@max-arnold no objections.
I also looked at your docs again and saw the mentioning of CITIES_LIGHT_INCLUDE_CITY_TYPES. I guess it was not clear to me, what that actually does. Your explanation definitely cleared that up.

Have a great weekend.

**Comment by max-arnold** [comment]
Michael @greenday2 found another reason why some cities are skipped (2339 ignored PPLX records is less than half of reported 6000). The reason is that all cities with the same (Country.id, Region.id, City.name) are considered duplicate:

https://github.com/yourlabs/django-cities-light/blob/stable/3.x.x/cities_light/management/commands/cities_light.py#L344

@jpic Is there any valid reason why geoname_id is not the primary city lookup method (slug uniqueness or something like that)? I found this thread https://groups.google.com/forum/#!topic/yourlabs/aYwK3UgbAd8 and I think we can fix this issue.

**Comment by jpic** [comment]
Looks like it would be even better using geoname_id to update.

Nice research.

:guitar:

**Comment by max-arnold** [comment]
@vp92 We are working on this, but it will take some time due to current workload.

**Comment by mbaragiola** [comment]
Are there any work-arounds in the meantime?

**Comment by max-arnold** [comment]
@vp92 @mbaragiola You can try this (highly experimental) branch https://github.com/max-arnold/django-cities-light/commits/update-by-geoname-id

I'd like to hear any feedback regarding successful imports and number of imported cities which were peviously missing.

Please note though, that it has different database schema (new migrations) and I can't give any guarantees of compatibility with future releases, so once it is merged you will probably need to recreate all tables from scratch.

**Comment by mbaragiola** [comment]
Are you going to make this change permanent?

**Comment by max-arnold** [comment]
@mbaragiola Eventually yes, but current patch has some flaws I need to solve first. I did partial rebase in October, but haven't finished it yet due to personal reasons. I plan to allocate some time during Christmas holidays.

**Comment by max-arnold** [comment]
@vp92 @mbaragiola Could you please re-test my branch and check if it imports everything you need?  https://github.com/max-arnold/django-cities-light/commits/update-by-geoname-id
