### ISSUE TITLE
Update django-autocomplete-light requirement (contrib)

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-cities-light#119]

**Comment by max-arnold** [comment]
@jpic Do you have any ideas on how to upgrade this? The API has changed a lot between 1.4.14 and current 3.2.9 and neither me nor @greenday2 are familiar with contrib use cases and the library itself.

**Comment by max-arnold** [comment]
@jpic This is the only contrib module and stale dependency without tests.  Any ideas on how to upgrade it and for which use cases to test?

**Comment by jpic** [comment]
Removal proposed in #157

**Comment by berkerpeksag** [comment]
PR #157 has been merged. I think this can be closed now.
