### ISSUE TITLE
 'BaseCommand' has no attribute 'option_list'

### ISSUE THREAD

**Issue by dogukankotan** [yourlabs/django-cities-light#122]
cities_light_fixtures  needs to be updated to change 'option_list' to add_argument

**Comment by jpic** [comment]
Perhaps something like that will work ?
https://github.com/safarijv/sbo-selenium/pull/8/files​

**Comment by dogukankotan** [comment]
Thanks! It worked for Django 1.10.

**Comment by max-arnold** [comment]
@jpic I guess it is time to drop support for Django < 1.8. I'll send a PR in the next few days.

**Comment by jpic** [comment]
@dogukankotan could you perhaps contribute this ?

@max-arnold in that case we could help by reviewing @dogukankotan's pr ?

**Comment by jpic** [comment]
And yes, support for < 1.8  has been dropped upstream so we can drop it too !

**Comment by dogukankotan** [comment]
I cloned to add PR. However, I realized that you have added add_arguments function to your codes. I installed this from using pip. I think that I am using python 3 so I installed old version of it. I  have tested with your clones, it's okay so I it's not needed PR.

**Comment by jpic** [comment]
Right, I had implemented dj110 support back in May in PR #118 so that's **months** before the official release.

Always test against master :)
