### ISSUE TITLE
Database Not Populated (Sqlite)

### ISSUE THREAD

**Issue by chris-y-meyers** [yourlabs/django-cities-light#123]
Hi,

I am trying to integrate this app into my Django project.
However no matter what I do the Sqlite database is not populated with downloaded data entries.
Even by running `manage.py cities_light –force-all`.
Data is properly downloaded to '_cities_light/data_' within my Python venv.

Am using Django 1.10 on an Ubuntu environment.
Database is Sqlite.

Settings are as follows:
```
CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en', 'no', 'abbr']
CITIES_LIGHT_INCLUDE_COUNTRIES = []
CITIES_LIGHT_INCLUDE_CITY_TYPES = [
    'PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC',
    'PPLF', 'PPLG', 'PPLL', 'PPLR', 'PPLS', 'STLMT',
]
```

Also my model in project is as:
```
from cities_light.models import City, Region, Country

class UserAddress(models.Model):
	user = models.ForeignKey(User)
	name = models.CharField(_('Name'), max_length=255, blank=False)
	address = models.CharField(_('Address'), max_length=255, blank=False)
	city = models.ForeignKey(City, blank=False)
	province = models.ForeignKey(Region, blank=False)
	country = models.ForeignKey(Country, blank=False)
	telephone = models.CharField(_('Telephone'), max_length=255, blank=True, null=True)

	def __unicode__(self):
		return u'%s' % getattr(self, 'name')
```

Is there something wrong in my configuration ?
Or is using Sqlite causing the problem.

Thanks

**Comment by jpic** [comment]
Seems like this `CITIES_LIGHT_INCLUDE_COUNTRIES = []` excludes all countries. Perhaps remove that setting and let the default `None` take place ?

**Comment by chris-y-meyers** [comment]
Ah yes true. Thanks !!
