### ISSUE TITLE
search_names removed space 

### ISSUE THREAD

**Issue by fuji246** [yourlabs/django-cities-light#134]
Trying to search "san jose" but doesn't get any result, the search_names look like removed all spaces.

```
sqlite> select search_names from cities_light_city where "cities_light_city"."search_names" LIKE '%sanjose%';
sanjoseamerica sanjosecaliforniaamerica sanjosecaliforniarepublicamerica sanjosecaliforniarepublicunitedstates sanjosecaliforniarepublicunitedstatesofamerica sanjosecaliforniaunitedstates sanjosecaliforniaunitedstatesofamerica sanjosegoldenstateamerica sanjosegoldenstateunitedstates sanjosegoldenstateunitedstatesofamerica sanjosestateofcaliforniaamerica sanjosestateofcaliforniaunitedstates sanjosestateofcaliforniaunitedstatesofamerica sanjoseunitedstates sanjoseunitedstatesofamerica
southsanjosehillscaliforniaunitedstates southsanjosehillsunitedstates
```

**Comment by jpic** [comment]
I'm a bit confused, your example here shows search working as expected.

What's not working as expected exactly ?

**Comment by fuji246** [comment]
not working expected, i search "San Jose", and no matches, search "sanjose"
works, but that is not what expected

2016-10-30 4:45 GMT-07:00 James Pic <notifications@github.com>:

**Comment by max-arnold** [comment]
The search works as expected in django admin, because it uses `to_search` function and removes any spaces from query too. Do you use cities_light/contrib modules for search, or just this SQL query?

**Comment by fuji246** [comment]
i use cities_light/contrib

2016-10-30 10:12 GMT-07:00 Max Arnold <notifications@github.com>:

**Comment by max-arnold** [comment]
Michael @greenday2 is working on this issue.

**Comment by max-arnold** [comment]
This is fixed, just need to allocate some time for review and PR: https://github.com/greenday2/django-cities-light/commit/17d531f3d87e4c56234d2671663ec04eb21626a6

**Comment by max-arnold** [comment]
Merged in https://github.com/yourlabs/django-cities-light/pull/155, closing.
