### ISSUE TITLE
Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the CountrySerializer serializer.

### ISSUE THREAD

**Issue by shahzad31** [yourlabs/django-cities-light#136]
OS Version: Ubuntu 16.04
Python version: 3.5.2
Django version:1.9.7
App version: 3.3.0
How to reproduce this bug:
You need to access /countries access point exposed by contrib rest-framework, 
Excepted result:
API should return countries list populated in database
Actual result:
Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the CountrySerializer serializer.

**Comment by max-arnold** [comment]
@greenday2 It would be nice to have some tests for contrib/restframework3.py

**Comment by max-arnold** [comment]
Contrib tests were added in https://github.com/yourlabs/django-cities-light/pull/155, closing.
