### ISSUE TITLE
Lost migration

### ISSUE THREAD

**Issue by Egregors** [yourlabs/django-cities-light#147]
Hi. Thanks for great project! 

I create City, Country, Region models in my own models file, exactly like in documentations.
Next, I make a migrations, but except my own app migration, Django create migration for cities-light  in third-party apps folder:

```
...
Migrations for 'cities_light':
  env/src/cities-light/cities_light/migrations/0008_auto_20170309_0153.py:
    - Alter unique_together for city (0 constraint(s))
    - Remove field country from city
    - Remove field region from city
    - Alter unique_together for region (0 constraint(s))
    - Remove field country from region
    - Delete model City
    - Delete model Country
    - Delete model Region
```

```
# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0007_make_country_name_not_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]

```

My project deploy by CI, and just apply migrations only from project src. Third-party apps installs clearly every rebuild. So, I can't put this migration into my project src.

Is it correct behavior? Or this is kind of my mistake?

**Comment by max-arnold** [comment]
1. Did you change the `CITIES_LIGHT_APP_NAME` setting to point to your app with the custom models?
2. On which version of django-cities-light you first created your custom models?
3. On which version you started to see this problem with migrations?

**Comment by max-arnold** [comment]
@Egregors I think instead of running:

```
./manage.py makemigrations
```

you need to run:

```
./manage.py makemigrations your_custom_models_app
```

Also you may try to experiment with the following setting (may break something):

```
MIGRATION_MODULES = {'cities_light': 'your_custom_models_app.migrations'}
```

**Comment by max-arnold** [comment]
@st4lk If you have some time, please look into this issue with custom models. I never used this feature and you as its author are better positioned to troubleshoot this. Maybe at least the docs should be updated (they still recommend to run deprecated `manage.py syncdb`)

**Comment by Egregors** [comment]
@max-arnold 

> Did you change the CITIES_LIGHT_APP_NAME setting to point to your app with the custom models?
> On which version of django-cities-light you first created your custom models?
> On which version you started to see this problem with migrations?

1. Yes
2. stable/3.x.x
3. stable/3.x.x

> 
> Also you may try to experiment with the following setting (may break something):
> 
> `MIGRATION_MODULES = {'cities_light': 'your_custom_models_app.migrations'}`

This is fix my problem. Now lost migration put in my app folder.

As I see, little bug in Django `make_model_tuple` func may be cause of this problem:

```
from django.utils import six


def make_model_tuple(model):
    """
    Takes a model or a string of the form "app_label.ModelName" and returns a
    corresponding ("app_label", "modelname") tuple. If a tuple is passed in,
    it's assumed to be a valid model tuple already and returned unchanged.
    """
    try:
        if isinstance(model, tuple):
            model_tuple = model
        elif isinstance(model, six.string_types):
            app_label, model_name = model.split(".")
            model_tuple = app_label, model_name.lower()
        else:
            model_tuple = model._meta.app_label, model._meta.model_name
        assert len(model_tuple) == 2
        return model_tuple
    except (ValueError, AssertionError):
        raise ValueError(
            "Invalid model reference '%s'. String model references "
            "must be of the form 'app_label.ModelName'." % model
        )

```

Django does not expect app name with prefix, like «projectname.appname».

In my project all apps has prefix (as @pydanny [advises)](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/apps.py#L5)

So I can't set CITIES_LIGHT_APP_NAME as "prefix.app_name":

`
ValueError: Invalid model reference 'prefix.app_name.Region'. String model references must be of the form 'app_label.ModelName'.`

Probably, you may update your `get_cities_model` func to catch this. I'm not sure.

By the way, 
```
MIGRATION_MODULES = {
    'cities_light': 'prefix.app_name.migrations'
}
```
is still solve this case. 

Thank you very much.

**Comment by max-arnold** [comment]
@Egregors I updated the comment, try this (as of 1.9 https://docs.djangoproject.com/en/1.10/ref/settings/#migration-modules):

```
MIGRATION_MODULES = {
    'cities_light': None
}
```

**Comment by max-arnold** [comment]
This will disable built in cities_light migrations and you will be able to create your own migrations using `./manage.py makemigrations your_custom_models_app`.

**Comment by Egregors** [comment]
This is exactly what I need. Thanks.

**Comment by max-arnold** [comment]
I'll update the docs
