### ISSUE TITLE
How to get UTC/GMT Offset Field?

### ISSUE THREAD

**Issue by pije76** [yourlabs/django-cities-light#158]
This package looks great. Thanks for it!
And I need to add UTC Offset field (in +/- HH:MM format) to be filled from geonames database (timeZones.txt) by using this: [http://django-cities-light.readthedocs.io/en/stable-3.x.x/full.html#steps-to-customise-cities-light-models]

How to get that on AbstractCity's models?

**Comment by max-arnold** [comment]
We already have the `City.timezone` field, you can try it using master branch or wait for the upcoming release: https://github.com/yourlabs/django-cities-light/issues/153 https://github.com/yourlabs/django-cities-light/issues/156

**Comment by pije76** [comment]
Great! I will waiting for next release.
Keep good job!
