### ISSUE TITLE
Add support for django 2.0

### ISSUE THREAD

**Issue by anjali-dhanuka** [yourlabs/django-cities-light#166]
On_delete argument to be passed in model and migration fields
In django 2.0 all the functions of django.core.url.resolvers and django.url.confs are placed in django.urls library so the libraries needs to be changed in the urls file

**Comment by max-arnold** [comment]
Check out `dj2` branch: https://github.com/yourlabs/django-cities-light/commits/dj2

**Comment by max-arnold** [comment]
@jpic Any plans for new release? We have a number of issues related to Django version support: #156 #153

**Comment by jpic** [comment]
Sure, you want a release as -rc or direct 3.4.0 ?

**Comment by max-arnold** [comment]
3.4.0

**Comment by TraMZzz** [comment]
This feature very important for me, when you can release it?

**Comment by jpic** [comment]
3.4.0 released
