### ISSUE TITLE
Compatibility with django 2.0 

### ISSUE THREAD

**Issue by younes-alouani** [yourlabs/django-cities-light#177]
After adding django-cities to my packages and running server. I got this : 

> from django.core.urlresolvers import get_callable
> ImportError: No module named 'django.core.urlresolvers'

To solve this, you have to change the settings of : 

> /lib/python3.5/site-packages/autoslug/settings.py

replace from django.core.urlresolvers import with from django.urls.

**Comment by jpic** [comment]
Ok for import compatibility pull requests.

**Comment by younes-alouani** [comment]
For people worrying about backward compatibility, they can use this instead  : 
try:
  from django.core.urlresolvers import get_callable
except :
  from django.urls import get_callable
