### ISSUE TITLE
Can Django-Airports will work

### ISSUE THREAD

**Issue by mmihir82** [yourlabs/django-cities-light#201]
Hello,
Is it compatible, with django-airports? I'm trying to implement the need to populate a dropdown field based on Country, Region, City and get Airport code.

**Comment by mpasternak** [comment]
What do you mean by “compatible”?

**Comment by mmihir82** [comment]
Hello, I have enable django-cities-light and I would like to use django-Airportcode with cities-light. I enable and it throw errors. So wondering if airports and cities-light works together?

**Comment by mpasternak** [comment]
Please provide a minimal non working code sample in a form of github repository together with the trace back and reopen
