### ISSUE TITLE
Cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

### ISSUE THREAD

**Issue by sokffa** [yourlabs/django-cities-light#205]
I installed cities_light and when i try to migrate it i get this error  : 
cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

I have python 3.7.3 , Django 3.0.2

**Comment by vahid75** [comment]
> I installed cities_light and when i try to migrate it i get this error :
> cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
> 
> I have python 3.7.3 , Django 3.0.2

i ran this today and i got thia error too. i think according to https://stackoverflow.com/questions/20741754/python-2-unicode-compatible-error
we should change it module . if i will could fix this error, i update this comment

**Comment by GHawk** [comment]
> > I installed cities_light and when i try to migrate it i get this error :
> > cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
> > I have python 3.7.3 , Django 3.0.2
> 
> i ran this today and i got thia error too. i think according to https://stackoverflow.com/questions/20741754/python-2-unicode-compatible-error
> we should change it module . if i will could fix this error, i update this comment
> 
> update:
> in file cities_light/abstract_models.py
> change 'django.utils.encoding' to 'six'
> . migrate it . done

Can you specify?.. do you mean to change:
`from django.utils.encoding import force_tex` to `from six import force_tex` or `from django.utils.encodig.six import force_tex`

exactly what do i need to change

**Comment by vahid75** [comment]
> > > I installed cities_light and when i try to migrate it i get this error :
> > > cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
> > > I have python 3.7.3 , Django 3.0.2
> > 
> > 
> > i ran this today and i got thia error too. i think according to https://stackoverflow.com/questions/20741754/python-2-unicode-compatible-error
> > we should change it module . if i will could fix this error, i update this comment
> > update:
> > in file cities_light/abstract_models.py
> > change 'django.utils.encoding' to 'six'
> > . migrate it . done
> 
> Can you specify?.. do you mean to change:
> `from django.utils.encoding import force_tex` to `from six import force_tex` or `from django.utils.encodig.six import force_tex`
> 
> exactly what do i need to change
change this line
from django.utils.encoding import python_2_unicode_compatible
to :
from six import python_2_unicode_compatible

**Comment by GHawk** [comment]
it worked! thanks!

**Comment by farridav** [comment]
Any news on when this fix can make it into a release? I imagine a lot of new projects are starting with Django 3+ and this breaking change will make this awesome package unusable.

Modifying this package in-place isnt currently an option for me. Thanks

**Comment by bomba1990** [comment]
I think will be good is the maintainer of the repo-add some contributors or allow other people to help to improve this package. Because we use this in our company on many projects and we can contribute to improve the project.

**Comment by jpic** [comment]
Released in 3.5.1, please confirm resolution
