### ISSUE TITLE
DRF 3.0 compatibility

### ISSUE THREAD

**Issue by moimael** [yourlabs/django-cities-light#71]
Hi,

It would be great to have DRF 3.0 compatibility.

Apparently from the first test i did, you just have to add the queryset attribute on custom Fields. (except url)

Thanks !

**Comment by jonasspott** [comment]
Hi James
I am aware of your guidelines, but do you have any update on a DRF3 support?

**Comment by jpic** [comment]
Not me, @moimael maybe ?

**Comment by jpic** [comment]
But there's no reason you can't use django-cities-light with DRF3, after all cities-light is just 3 models !

**Comment by jpic** [comment]
It's supported to use any version of drf with django-cities-light
(which is just 3 rather basic models ^^).

However, @moimael contributed updated django-restframework support.
