### ISSUE TITLE
Python 3.3 and django-cities-light on Windows 8.1 don't work.

### ISSUE THREAD

**Issue by mikaelosterberg** [yourlabs/django-cities-light#75]
When I run "manage.py cities_light" django-cities-light dies.
C:\Git\XXX\src>manage.py cities_light
RAM used: ?? kB Time: 0:00:00 Done: 100%|#####################################|
Traceback (most recent call last):
  File "C:\Git\XXX\src\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python33\lib\site-packages\django\core\management\__init__.py", line
385, in execute_from_command_line
    utility.execute()
  File "C:\Python33\lib\site-packages\django\core\management\__init__.py", line
377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python33\lib\site-packages\django\core\management\base.py", line 288,
 in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\Python33\lib\site-packages\django\core\management\base.py", line 338,
 in execute
    output = self.handle(*args, **options)
  File "C:\Python33\lib\site-packages\django_cities_light-3.0.3-py3.3.egg\cities
_light\management\commands\cities_light.py", line 156, in handle
    progress = progressbar.ProgressBar(maxval=geonames.num_lines(),
  File "C:\Python33\lib\site-packages\django_cities_light-3.0.3-py3.3.egg\cities
_light\geonames.py", line 98, in num_lines
    return sum(1 for line in open(self.file_path))
  File "C:\Python33\lib\site-packages\django_cities_light-3.0.3-py3.3.egg\cities_light\geonames.py", line 98, in <genexpr>
    return sum(1 for line in open(self.file_path))
  File "C:\Python33\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 404: character maps to <undefined>

Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:37:12) [MSC v.1600 32 bit (In
tel)] on win32
And latest django from pip on 2015-01-25.

Any ide on how to solve this?

**Comment by jpic** [comment]
On Sun, Jan 25, 2015 at 9:57 PM, Mikael Österberg <notifications@github.com>
wrote:

> cp1252


It should be using utf8

I don't know windows though, but i'd suggest looking for files like site.py
which are a bad practice and may cause this kind of issue. Not sure though,
maybe ask stackoverflow, but pull requests are welcome.

**Comment by mikaelosterberg** [comment]
No site.py file that i can delete whiteout python dies.
looking at the encoding.

**Comment by jpic** [comment]
On Mon, Jan 26, 2015 at 12:18 PM, Mikael Österberg <notifications@github.com
> wrote:

> No site.py file that i can delete whiteout python dies.
>
See:
https://docs.python.org/2/howto/unicode.html

-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by mikaelosterberg** [comment]
Believe i found it.
open() uses different encoding on different systems like
- UTF-8 on Mac OS X, most Linux distributions
- ANSI code page on Windows, e.g. cp1252 (close to ISO-8859-1) in
Western Europe, cp952 in Japan, ...
https://mail.python.org/pipermail/python-dev/2011-June/112086.html

**Comment by jpic** [comment]
N1 geonames data is utf8 so we need to force that.
Le 26 janv. 2015 13:22, "Mikael Österberg" <notifications@github.com> a
écrit :

**Comment by mikaelosterberg** [comment]
Pull request #77 fixes this issue.
