### ISSUE TITLE
Named indexes from geonames

### ISSUE THREAD

**Issue by st4lk** [yourlabs/django-cities-light#82]
Currently access to geonames item is done by index, for example `item[7]`, but it will be useful to have named indexes, i.e. `item[ICountry.code]`.
I've done it in commit 5d7ea329d32b431cd43b57beb57bfecb4df16220, but looks like it slows down the import process, as travis get stuck with message:

> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated

I think choices are:
- undo the commit and use simple integer indexes
- find another way with named indexes and performance

**Comment by jpic** [comment]
Sometimes travis is a bit slow anyway, could you try again in a branch ?

I'm all for using meaningful index variables though.

**Comment by st4lk** [comment]
Yes, but now i'm not sure, that this changes have big impact on performance. I've undo the changes, but travis still can't finish all jobs. As i see in history, it happen sometimes.

**Comment by st4lk** [comment]
Strange, after i manually restarted travis jobs - they pass. Is it known issue?

**Comment by jpic** [comment]
I think it's mentioned in the maintainer guide in docs.yourlabs.org​

**Comment by st4lk** [comment]
Ok, sorry to not read it earlier

**Comment by jpic** [comment]
I'll remember to link it next time I invite someone to join, no worries xD

BTW you might like to join #yourlabs on irc.freenode.net

**Comment by jpic** [comment]
Fixed by #83
