### ISSUE TITLE
Error since upgrading to 3.1.0

### ISSUE THREAD

**Issue by moimael** [yourlabs/django-cities-light#85]
Since i upgraded i hit this issue when applying migrations :

```
LookupError: No installed app with label 'cities_light'
...
ValueError: Lookup failed for model referenced by field users.User.city: cities_light.City
```

Any pointers ?

Thx !

**Comment by st4lk** [comment]
Hi, thanks for reporting!
I'll check this soon.

**Comment by st4lk** [comment]
Can you please precise your django version?

**Comment by jpic** [comment]
Full traceback please ?

**Comment by moimael** [comment]
It was Django 1.7.7. I was in a hurry to get it work (deadlines..) so I deleted all migrations and started fresh. So no full traceback, sry.

**Comment by jpic** [comment]
Ok don't worry about it bro in the future don't forget the full traceback
B-)

Could you tell more about it ? In french si ça te prends moins de temps...
Est-ce-que failing migrations were from your app with models with relation
to cities lights models or were them from cities light app itself ?

Merci frère B)

**Comment by st4lk** [comment]
Currently can't reproduce the problem.
Here what i tried.

Model:

    class User(models.Model):
        title = models.CharField("Title", max_length=50, null=True, blank=True)
        city = models.ForeignKey("cities_light.City", null=True, blank=True)

#### From django 1.6 with south to django 1.7 without south

- pip install -U django==1.6.11
- pip install south  # add to INSTALLED_APPS
- pip install django-cities-light==2.3.0  # add to INSTALLED_APPS
- python manage.py syncdb
- python manage.py migrate cities_light # south migrations 0015
- pip install -U django-cities-light==2.3.1
- python manage.py migrate cities_light # south migrations 0017
- pip install -U django==1.7.7
- pip install -U django-cities-light==3.1.0
- follow guide from https://docs.djangoproject.com/en/1.7/topics/migrations/#upgrading-from-south
    - remove 'south' from INSTALLED_APPS
    - python manage.py makemigrations
    - python manage.py migrate --fake cities_light 0002
    - python manage.py migrate cities_light

#### From django 1.6 with south to django 1.6 with south

- pip install -U django==1.6.11
- pip install django-cities-light==2.3.0
- python manage.py syncdb
- python manage.py migrate cities_light # south migrations 0015
- pip install -U django-cities-light==3.1.0
- add settings.SOUTH_MIGRATION_MODULES as discribed in http://django-cities-light.readthedocs.org/en/stable-3.x.x/#installation
- python manage.py migrate cities_light # south migrations 0017

Everything seems working properly.

@moimael some details will be helpful, i.e.
- From what version of django-cities-light do you upgrade?
- What migrations were applied before upgrading?

**Comment by jpic** [comment]
Apparently there's nothing else we can do about this. Otherwise, please re-open.
