### ISSUE TITLE
No handlers could be found for logger "cities_light"

### ISSUE THREAD

**Issue by duaneking** [yourlabs/django-cities-light#93]
I get this output every time I get an error from cities_light, At first glance it looks like its not set up to respect logging when verbosity is set.

If I do the bad but useful thing and add the following to the cities_light command just after the logger is created:

    logger = logging.getLogger('cities_light')
    logger.setLevel(logging.DEBUG)

    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(ch)

... I get useful data in the error output.  If you want I can submit a patch.  Looks like the increased output shows that a lot of slugs are failing to import due to non-unique slugs and that is what may be creating #92 and so cities such as Lima Puru and other large important cities are never being imported.

**Comment by jpic** [comment]
You can configure a cities_light logger in django settings: https://docs.djangoproject.com/en/1.8/topics/logging/

As specified in the third step of the docs: http://django-cities-light.readthedocs.org/en/stable-2.x.x/database.html#configure-logging

**Comment by duaneking** [comment]
Yes and thank you; The point I'm trying to make is that if you do a 2 hour failed import it does not matter what is configured for logging,, you want error output. :)

**Comment by jpic** [comment]
On Tue, Jun 23, 2015 at 3:44 AM, Duane King <notifications@github.com>
wrote:

> Yes and thank you; The point I'm trying to make is that if you do a 2 hour
> failed import it does not matter what is configured for logging,, you want
> error output. :)


I don't understand what you mean. If you don't want logging then don't
configure it, but you want login, so do configure it.

-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.
