### ISSUE TITLE
More limited cities15000.zip file is used instead of far more complete cities1000.zip for data source.

### ISSUE THREAD

**Issue by duaneking** [yourlabs/django-cities-light#94]
# Why this is not a feature request.
I don't consider this a feature request because in this case the data set is simply being arbitrarily restricted due to the use of the wrong file as input. Its not a feature, just the wrong input is being used.

# Fix Suspected Difficulty
Should be a simple fix.

# Proposed solution.
My opinion is that the correct (larger) file should be the default input, and a override should be added via the command line so if if somebody wanted to change it, they can.

**Comment by jpic** [comment]
Did you see django-cities-light's settings documentation ?

http://django-cities-light.readthedocs.org/en/stable-2.x.x/full.html#module-cities_light.settings

**Comment by duaneking** [comment]
Yes, the problem is that the wrong default is used.

In addition, there is no documentation of what is being overridden.  There is no mention of the identified options available. Editing the source to say "use this instead" is great but to many its a function of usability to have the command line option.

**Comment by jpic** [comment]
On Tue, Jun 23, 2015 at 3:43 AM, Duane King <notifications@github.com>
wrote:

> Yes, the problem is that the wrong default is used.
>
> It's wrong **for you**.

> In addition, there is no documentation of what is being overridden. There
> is no mention of the identified options available. Editing the source to
> say "use this instead" is great but to many its a function of usability to
> have the command line option.
>
Insufficient for breaking BC and changing the default.

--
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by duaneking** [comment]
Why not add an optional command line that doesn't BC?

**Comment by jpic** [comment]
What kind of optional command line that doesn't break BC ?

Isn't it easier to just set the sources you want in your settings ?

**Comment by duaneking** [comment]
No it does not, because most builds and deployments are automated and so needing to edit the code on the fly kills that effort.

**Comment by jpic** [comment]
Are you saying that your automatic builds and deployment system are unable to add a settings file with the right settings and that all default settings should be the one you want ? Sounds like a lot of fun :D

On the other hand we have automated CI, and we want to use the smallest dataset, so if we change the default to your needs this means we'll have to update CI ("backward compatibility break").

What automated deployment system do you use ? Ansible ? Salt ? Chef ? Puppet ? Fabric ? Capistrano ? These are all able to change a setting in a file or to generate a settings file from a template, so, I'm really curious about how you're doing it in such a way that requires the default in this app to be the setting you want ^^

And if you don't want to generate a settings file then you could go 12factor and allow default override with environment variable (hey why not use [django-environ](https://github.com/joke2k/django-environ) for that while you're at it ?)
